# Generated by Django 2.2.6 on 2021-12-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211203_1231'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='События',
        ),
    ]
