# Generated by Django 2.2.6 on 2021-12-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211203_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-pub_date'], 'verbose_name': 'События'},
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
    ]
