# Generated by Django 2.2.6 on 2021-12-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211203_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-pub_date'], 'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
    ]
