# Generated by Django 2.2.6 on 2021-12-11 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20211203_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='place',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='number_of_purchased_tickets',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во купленных билетов'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='number_of_available_tickets',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во доступных билетов'),
        ),
    ]
